name: 20 CD Pipeline

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    needs: [build-test-docker, terraform-validate]
    steps:
      - name: Say Hello
        run: echo "Hello from CD pipeline!"
