name: 20 CD Pipeline

on:
  workflow_run:
    workflows: ["10 CI Pipeline"] # This pipeline runs after the CI pipeline.
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Don't run if CI run failed
    steps:
      - name: Say Hello
        run: echo "Hello from CD pipeline!"
