name: 20 CD Pipeline

on:
  workflow_run:
    workflows: ["10 CI Pipeline"] # This pipeline runs after the CI pipeline.
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    # Only run this job (and workflow) if initially triggered by push to main and CI workflow succeeded
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    environment: default
    env:
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZ_SP_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_SP_CLIENT_SECRET }}
      TF_HOME: terraform/
      tf_backend_rg: ${{ secrets.AZ_TF_BACKEND_RG}}
      tf_backend_sa_name: ${{ secrets.AZ_TF_BACKEND_SA_NAME}}
      tf_backend_container: ${{ secrets.AZ_TF_BACKEND_CONTAINER}}

    steps:
      - uses: hashicorp/setup-terraform@v3

      - name: Downloading Terraform Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform
          path: ${{ env.TF_HOME }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Init
        run: |
          cd $TF_HOME
          terraform -version
          terraform init \
            -backend-config="resource_group_name=$tf_backend_rg" \
            -backend-config="storage_account_name=$tf_backend_sa_name" \
            -backend-config="container_name=$tf_backend_container" \
            -backend-config="key=webg-test.tfstate"
          cd -

      - name: Terraform Plan
        run: |
          cd $TF_HOME
          terraform plan -out=plan.out
          cd -

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-test
          path: ${{ env.TF_HOME }}/plan.out
