name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: App Build & Sonar Cloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw clean install
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TB-EIT_devsecops-sandbox
          echo '## Sonar Cloud Scan Approval Gate' >> $GITHUB_STEP_SUMMARY
          echo '[![Quality gate](https://sonarcloud.io/api/project_badges/quality_gate?project=TB-EIT_devsecops-sandbox)](https://sonarcloud.io/summary/new_code?id=TB-EIT_devsecops-sandbox)' >> $GITHUB_STEP_SUMMARY

      - name: Upload App Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webgoat-jar
          path: target/webgoat-*.jar

      - name: Build Docker image
        run: |
          docker build -f Dockerfile . -t tbeit/webgoat:$GITHUB_RUN_ID

      - name: Docker Hub Login
        run: docker login -u tbeit -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.7.0
        with:
          command: quickview,cves,recommendations
          only-severities: critical,high
          # exit-code: true # Fails the whole job if the vulnerabilities are found

      - name: Push Docker Image to Docker Hub
        run: docker push tbeit/webgoat:$GITHUB_RUN_ID
