name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: App Build
        run: |
          ./mvnw clean install

      - name: Build Docker image
        run: |
          docker build -f Dockerfile . -t tbeit/webgoat:$GITHUB_RUN_ID

      - name: Docker Hub Login
        run: docker login -u tbeit -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.7.0
        with:
          command: quickview,compare,cves,recommendations
          image: tbeit/webgoat:$GITHUB_RUN_ID

      - name: Push Docker Image to Docker Hub
        run: docker push tbeit/webgoat:$GITHUB_RUN_ID
